### ISSUE TITLE
Your app includes non-compliant SDK version

### ISSUE THREAD

**Issue by skwasimakram13** [solodroidx/solodroid-ads-sdk#3]
Your app includes non-compliant SDK version
Issue found: [User data](https://support.google.com/googleplay/android-developer/answer/10144311) policy issue by SDK

Your app com.demoody.packagename version code 27 includes SDK com.startapp:inapp-sdk, 4.8.11, or an SDK that one of your libraries depends on, potentially facilitates the transmission or collection of installed packages without meeting the prominent disclosure guidelines and/or privacy policy guidelines.

Please ensure that you are being transparent in how you handle user data (e.g. information collected from or about a user, including device information). That means disclosing your app's access, collection, use and sharing of the data, and limiting the use of the data to the purposes disclosed. If your app handles sensitive user data, then you must follow the [User data](https://support.google.com/googleplay/android-developer/answer/10144311) policy.

Starting from 28 January 2023 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User data](https://support.google.com/googleplay/android-developer/answer/10144311) policy will be blocked from release. You may consider upgrading to a policy-compliant version of this SDK that does not include the violating code, if available from your SDK provider, moving to another SDK or removing this SDK.

According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for further information.

ACTION REQUIRED: Upload a compliant version AND deactivate the non-compliant version

Read through the [User data](https://support.google.com/googleplay/android-developer/answer/10144311) policies for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit).If you do not deactivate the non-compliant APK, all your live APKs may be removed due to this non-compliant APK.

Check that your app is compliant with all other [Developer Programme Policies](https://play.google.com/about/developer-content-policy). Additional enforcement could occur if there are further policy violations.

If you've reviewed the policy and feel our decision may have been in error, please get in touch with our [policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk&src=com.startapp:inapp-sdk).

Please upgrade com.startapp:inapp-sdk, 4.8.11 SDK to version 4.10.1

**Comment by solodroidx** [comment]
Hi, Please note, this library is already using latest startapp sdk 4.10.5, so there is no problem with the play store issue, make sure you've use the latest library version.

**Comment by skwasimakram13** [comment]
What is the latest version of solodroid-ads-sdk?

**Comment by solodroidx** [comment]
1.8.4
https://github.com/solodroidx/solodroid-ads-sdk/releases

---
Regards,
Solodroid
