### ISSUE TITLE
non compliant sdk

### ISSUE THREAD

**Issue by ScripticusKodius** [solodroidx/solodroid-ads-sdk#4]
Issue found: [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) Policy Issue by SDK

Your app com.********** version code 12 includes SDK com.startapp:inapp-sdk, or an SDK that one of your libraries depends on, potentially facilitates the transmission or collection of installed packages without meeting the prominent disclosure guidelines and/or privacy policy guidelines.

Please ensure that you are being transparent in how you handle user data (e.g., information collected from or about a user, including device information). That means disclosing your app's access, collection, use, and sharing of the data, and limiting the use of the data to the purposes disclosed. If your app handles sensitive user data, then you must follow the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) Policy.

Starting from January 28, 2023 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) Policy will be blocked from release. You may consider upgrading to a policy-compliant version of this SDK that does not include the violating code, if available from your SDK provider; moving to another SDK; or removing this SDK.

According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for further information.

ACTION REQUIRED: Upload a compliant version AND deactivate the noncompliant version

Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policies for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit).If you do not deactivate the non-compliant APK, all your live APKs may be removed due to this non-compliant APK.

**Comment by solodroidx** [comment]
You should use latest version of this library at least version 1.7.7 or newer, the latest version is 1.8.7 and already using newer startapp ads sdk: 4.10.5
